### ISSUE TITLE
Invis Users, Classes not spawning, Spawns pitch+yaw not stored

### ISSUE THREAD

**Issue by Kobe024** [MineSworn/UltimateArena#169]
Hi, first I just want to say thanks for such a great, easy to use, updated plugin. It has almost everything you could think of. However, there are some bugs that we have noticed that has caused us to stop using the plugin and I hope you can help fix them so we can use the plugin again cuz as I said before, it is an awesome plugin.

#1 - After using the arenas users sometimes appear invisible to each other, both in and out of arenas. Relogging sometimes fixes it but not always and this becomes a huge pain when there is an invis guy in pvp killing everyone else also just not being able to see others on the server. I saw a similar issue mentioned before where you said it's not really in UA's control about the invis thing but I think there may be a way you could fix it. I am currently using PvPArena plugin which is complicated as fuck but i've noticed a fixInvisibility option in the config and even a fixEvilInvisibility option. Maybe you could have a look at that and add something similar if possible. I looked through the code and found this although no idea if it will help - http://pastebin.com/RdzX9FHV

#2 - When lives are set to more than 1 users sometimes don't spawn in with a kit or will only spawn in with parts of the kit, not all of it. This has occured in CTF, KOTH and TEAMS.

#3 - When we set spawns, pitch and yaw are not stored so when users spawn in they are always facing south which ruins it a bit, also makes it a bit unfair if one person starts facing the other person and the other person is facing the back of the arena. I know this has already been mentioned but all you really said was that the pitch and yaw are not stored. I was wondering if you could maybe please maybe add them in as I'm sure a lot of people would appreciate it. It's just one of those small things that can make the plugin a LOT better. Again, I came across something I found online that might help, or not, not sure lol but I hope it will - http://pastebin.com/ZwD90rK0 I have looked into trying to do it myself but I'm too much of a noob to coding plugins.

I really hope u can help us fix these issues as we love your plugin.

**Comment by dmulloy2** [comment]
As for the 2nd one, I'm not exactly sure how to address that or where even to start. I haven't experienced it myself or had any other reports of it.

**Comment by bilal94** [comment]
Thanks so much for addressing this. In regards to the 2nd one I could maybe try to capture it on video if want so you can see it happening.

**Comment by dmulloy2** [comment]
Any more info on this?

**Comment by bilal94** [comment]
Sorry about late reply.

After testing dev build 838 - http://ci.minesworn.com/job/UltimateArena/838/ - the issue with the direction/pitch/yaw of spawns remains. When I set the spawns I am facing the direction I want it but when I join the arena i'm either looking straight up at the sun or right down at the floor. When I look in the arena config I can see the spawns like this:

team2spawn:
  ==: net.dmulloy2.ArenaLocation
  worldName: Games_World
  x: -122
  y: 64
  z: 681
  pitch: 0.74990505
  yaw: -92.24951

It seems to be that they are being set wrong because I checked with my in-game co-ords when I spawn in the arena and it seems to match with what is in the config. Here is a screenshot that might help. It corresponds to the config example I posted above - http://i.imgur.com/PfTc3m6.png

I have also noticed another weird thing now, once an arena in created, if i edit the arena config options via '/ua option type name option value' to set max players or default class then reload the config, it removes the spawns info from the arena.dat file.

As for the invisibility bug, didn't test it much cuz once the owner saw that the pitch/yaw issues were not fixed he removed the plugin. In the time that I did test it, mostly it seemed fine althought sometimes other users in the arena seem to flicker/go invis for a few secs but that could be to do with render distance or something since it only happened sometimes when they were like 15+ blocks away.

**Comment by dmulloy2** [comment]
The pitch and yaw may be applied incorrectly when the player spawns, I can look into that.

````/ua option```` has always been kinda buggy, I haven't had the time to investigate issues with it.

**Comment by dmulloy2** [comment]
Are spawns working correctly now?

**Comment by bilal94** [comment]
Yes, tested on a local server and they seem to be working perfectly now so thanks a lot. However, I have noticed some small issues like now when I create an arena join sign for some reason it reads [null Arena] on the first line. The sign still works and takes you to the arena and shows the name and players info. Here's a  [ss:](http://prnt.sc/e0ts22) Also, once the game is over, the scoreboard seems to stay on the screen sometimes but not really a biggie as relogging fixes it also, love the fact that you show k/d and killstreak!

Just wanted to add that I second the addition of feature #166 as it is very useful for when players in a lobby are ready but the lobby time still has like a minute to go. We could shorten lobby time of course but then we always get that one person who takes the piss to join the arena sometimes. With the iron block, u simply punch it to signify you are ready and if all players or a certain percentage of players ready up, it auto starts the game as if you were force-starting it using /ua start. Just would be way better if it happened via the iron block automatically rather than depending on if a staff member is in the game. Also, lots of users are already used to it from games live mobarea, spleef.

Thanks again

**Comment by dmulloy2** [comment]
Sign issue should be fixed in: https://github.com/MineSworn/UltimateArena/commit/daf71b745f0af4ec081bc7944cb5a83375739d55
